# Generated by Django 4.2 on 2023-12-28 20:39

import django.core.validators
from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=30, verbose_name='Sucursal')),
                ('fecha', models.CharField(max_length=30, verbose_name='Fecha')),
                ('admin', models.CharField(default='', max_length=70)),
                ('responsable', models.CharField(default='', max_length=70)),
                ('totalPlanilla', models.FloatField(default=0, verbose_name='Total Planilla Efectivo')),
                ('totalSegunDiarioCaja', models.FloatField(default=0, verbose_name='Total segun diario de caja')),
                ('diferencia', models.FloatField(default=0, verbose_name='Diferencia')),
                ('observaciones', models.TextField()),
                ('detalle', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CoeficientesListadePrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_nominal', models.IntegerField(verbose_name='Valor Nominal:')),
                ('cuota', models.IntegerField(verbose_name='Cuotas:')),
                ('porcentage', models.FloatField(verbose_name='Porcentage:')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoIdentificacion', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('CUIT', 'CUIT')], max_length=15, null=True, verbose_name='Tipo de identificacion:')),
                ('nroIdentificacion', models.CharField(blank=True, max_length=20, null=True, verbose_name='N° de Identificacion:')),
                ('tipoComprobante', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=3, null=True, verbose_name='Tipo de comprobante:')),
                ('nroComprobante', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nro de comprobante:')),
                ('denominacion', models.CharField(blank=True, max_length=60, null=True, verbose_name='Denominacion del ente:')),
                ('tipoMoneda', models.CharField(blank=True, choices=[('ARS', 'ARS'), ('USD', 'USD'), ('BRL', 'BRL')], max_length=3, null=True, verbose_name='Tipo de moneda:')),
                ('movimiento', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=8, verbose_name='Movimiento:')),
                ('dinero', models.FloatField(verbose_name='Dinero:')),
                ('metodoPago', models.CharField(max_length=30, verbose_name='Metodo de pago:')),
                ('sucursal', models.CharField(max_length=60, verbose_name='Sucursal:')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto:')),
                ('ente', models.CharField(max_length=40, verbose_name='Ente:')),
                ('fecha', models.CharField(max_length=10, verbose_name='Fecha:')),
                ('hora', models.CharField(max_length=6, verbose_name='Hora:')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_solicitud', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Ingrese un número válido')], verbose_name='Nro solicitud:')),
                ('modalidad', models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal'), ('Quincenal', 'Quincenal'), ('Mensual', 'Mensual')], default='', max_length=15, verbose_name='Modalidad:')),
                ('nro_cuotas', models.IntegerField()),
                ('nro_operacion', models.IntegerField(default=sales.models.Ventas.returnOperacion)),
                ('agencia', models.CharField(default='', max_length=30)),
                ('cambioTitularidadField', models.JSONField(blank=True, default=list, null=True)),
                ('adjudicado', models.JSONField(default=dict)),
                ('deBaja', models.JSONField(default=dict)),
                ('suspendida', models.BooleanField(default=False)),
                ('importe', models.FloatField(default=0, verbose_name='Importe:')),
                ('tasa_interes', models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Ingrese un número válido')], verbose_name='Tasa de Interes:')),
                ('primer_cuota', models.FloatField(default=0, verbose_name='Primer cuota:')),
                ('anticipo', models.IntegerField(default=0, verbose_name='Cuota de Inscripcion:')),
                ('intereses_generados', models.FloatField(default=0, verbose_name='Intereses Gen:')),
                ('importe_x_cuota', models.FloatField(default=0, verbose_name='Importe x Cuota:')),
                ('total_a_pagar', models.FloatField(default=0, verbose_name='Total a pagar:')),
                ('fecha', models.CharField(default='', max_length=30, verbose_name='Fecha:')),
                ('tipo_producto', models.CharField(default='', max_length=20)),
                ('paquete', models.CharField(default='', max_length=20)),
                ('nro_orden', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Ingrese un número válido')], verbose_name='Nro de Orden:')),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True, verbose_name='Obeservaciones:')),
                ('cuotas', models.JSONField(default=list)),
            ],
        ),
    ]
