# Generated by Django 4.2 on 2023-08-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='anticipo',
            field=models.IntegerField(default=0, verbose_name='Cuota de Inscripcion:'),
        ),
    ]
