# Generated by Django 4.2 on 2023-05-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.CharField(max_length=30, verbose_name='Fecha:'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='importe',
            field=models.FloatField(verbose_name='Importe:'),
        ),
    ]
