# Generated by Django 4.2 on 2025-04-26 13:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoCannon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_recibo', models.CharField(help_text='Número de recibo o comprobante, debe ser único por pago.', max_length=30, unique=True, verbose_name='N° de comprobante')),
                ('nro_cuota', models.PositiveSmallIntegerField(help_text='Cuota a la que aplica este pago (0 = inscripción).', validators=[django.core.validators.MinValueValidator(0)], verbose_name='N° de cuota')),
                ('fecha', models.CharField(default='26/04/2025 10:41', help_text='Fecha y hora en que se registró el pago.', max_length=30, verbose_name='Fecha de pago')),
                ('campana_de_pago', models.CharField(blank=True, help_text="Ej. 'Marzo 2025'. Se calcula en el save().", max_length=30, verbose_name='Campaña de pago')),
                ('monto', models.PositiveIntegerField(help_text='Importe entero del pago, mayor a cero.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Monto')),
                ('cobrador', models.ForeignKey(blank=True, help_text='Cuenta o persona que cobra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_cannon', to='sales.cuentacobranza')),
                ('metodo_pago', models.ForeignKey(blank=True, help_text='Método de pago utilizado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_cannon', to='sales.metodopago')),
                ('responsable_pago', models.ForeignKey(blank=True, help_text='Usuario interno responsable de la carga.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(help_text='Venta a la que pertenece este pago.', on_delete=django.db.models.deletion.CASCADE, related_name='pagos_cannon', to='sales.ventas')),
            ],
            options={
                'verbose_name': 'Pago Cannon',
                'verbose_name_plural': 'Pagos Cannon',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='pagocannon',
            index=models.Index(fields=['venta', 'nro_cuota'], name='sales_pagoc_venta_i_ee8c3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pagocannon',
            unique_together={('venta', 'nro_cuota', 'nro_recibo')},
        ),
    ]
