# Generated by Django 4.2 on 2025-04-08 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='agencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.sucursal'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='nro_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_nro_cliente', to='users.cliente'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_producto', to='products.products'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='supervisor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta_super_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ventas',
            name='vendedor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_ven_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientoexterno',
            name='agencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencia_movs', to='users.sucursal'),
        ),
        migrations.AddField(
            model_name='movimientoexterno',
            name='ente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ente_movs', to='sales.cuentacobranza'),
        ),
        migrations.AddField(
            model_name='movimientoexterno',
            name='metodoPago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metodo_movs', to='sales.metodopago'),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='agencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.sucursal'),
        ),
    ]
