# Generated by Django 4.2 on 2023-05-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_ventas_fecha_alter_ventas_importe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoeficientesListadePrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_nominal', models.IntegerField(verbose_name='Valor Nominal:')),
                ('cuota', models.IntegerField(verbose_name='Cuotas:')),
                ('porcentage', models.FloatField(verbose_name='Porcentage:')),
            ],
        ),
    ]
