# Generated by Django 4.2 on 2024-12-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='tipo_producto',
        ),
    ]
