# Generated by Django 4.2 on 2024-09-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='adjudicado',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='auditoria',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='deBaja',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
