# Generated by Django 4.2 on 2025-11-05 13:05

from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_ventas_gerente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventas',
            options={'ordering': ['nro_operacion']},
        ),
        migrations.RemoveIndex(
            model_name='ventas',
            name='sales_venta_agencia_65578c_idx',
        ),
        migrations.AlterField(
            model_name='pagocannon',
            name='fecha',
            field=models.CharField(default=sales.models.now_formatted, help_text='Fecha y hora en que se registró el pago.', max_length=30, verbose_name='Fecha de pago'),
        ),
    ]
