# Generated by Django 4.2 on 2026-02-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_ventas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocannon',
            name='moneda',
            field=models.CharField(default='ARS', help_text='Moneda en la que se realizó el pago.', max_length=4, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='pagocannon',
            name='tipo_cambio',
            field=models.FloatField(default=1.0, help_text='Tipo de cambio aplicado al momento del pago.', verbose_name='Tipo de cambio'),
        ),
    ]
