# Generated by Django 4.2 on 2023-05-02 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0003_coeficienteslistadeprecios'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='paquete',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_paquete', to='products.products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_producto', to='products.products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventas',
            name='tipo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_tipo_producto', to='products.products'),
        ),
    ]
