# Generated by Django 4.2 on 2024-09-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_ventas_adjudicado_alter_ventas_auditoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoexterno',
            name='campania',
            field=models.CharField(max_length=30, verbose_name='Campaña:'),
        ),
    ]
