# Generated by Django 4.2 on 2025-04-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_create_recibo_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocannon',
            name='fecha',
            field=models.CharField(default='26/04/2025 10:49', help_text='Fecha y hora en que se registró el pago.', max_length=30, verbose_name='Fecha de pago'),
        ),
    ]
