# Generated by Django 4.2 on 2025-04-29 20:09

from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_create_recibo_seq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='auditoria',
        ),
        migrations.AlterField(
            model_name='pagocannon',
            name='fecha',
            field=models.CharField(default=sales.models.PagoCannon.now_formatted, help_text='Fecha y hora en que se registró el pago.', max_length=30, verbose_name='Fecha de pago'),
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, help_text='Número incremental de la auditoría.')),
                ('realizada', models.BooleanField(default=False, help_text='Si la auditoría ya fue efectuada.')),
                ('graded', models.BooleanField(default=False, help_text='False: Si no aprobo | True: Si aprobo.')),
                ('reintegro_dinero', models.BooleanField(default=True, help_text='Si se reintegro dinero.')),
                ('motivo', models.CharField(blank=True, choices=[('Motivos personales', 'Motivos personales'), ('Arrepentimiento', 'Arrepentimiento'), ('Falta de conocimiento sobre el contrato', 'Falta de conocimiento sobre el contrato')], help_text='Motivo de la auditoría.', max_length=255)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios de la auditoría.')),
                ('fecha_hora', models.CharField(default=sales.models.Auditoria.now_formatted, help_text='Fecha y hora en que se creó este registro.', max_length=20)),
                ('venta', models.ForeignKey(help_text='Venta a la que corresponde este registro de auditoría.', on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='sales.ventas')),
            ],
            options={
                'ordering': ['venta', 'version'],
                'unique_together': {('venta', 'version')},
            },
        ),
    ]
