# Generated by Django 4.2 on 2023-08-28 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0003_alter_ventas_supervisor_alter_ventas_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='supervisor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta_super_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='vendedor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_ven_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
