# Generated by Django 4.2 on 2025-04-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_ventas_auditoria_alter_pagocannon_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditoria',
            old_name='graded',
            new_name='grade',
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='comentarios',
            field=models.TextField(blank=True, help_text='Comentarios de la auditoría.', null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='motivo',
            field=models.CharField(blank=True, choices=[('Motivos personales', 'Motivos personales'), ('Arrepentimiento', 'Arrepentimiento'), ('Falta de conocimiento sobre el contrato', 'Falta de conocimiento sobre el contrato')], help_text='Motivo de la auditoría.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='reintegro_dinero',
            field=models.BooleanField(default=False, help_text='Si se reintegro dinero.'),
        ),
    ]
