# Generated by Django 4.2 on 2023-08-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_ventas_supervisor_alter_ventas_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='nro_operacion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
