# Generated by Django 4.2 on 2023-05-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_ventas_paquete_ventas_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='paquete',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='tipo_producto',
            field=models.CharField(max_length=20),
        ),
    ]
