# Generated by Django 4.2 on 2025-04-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_pagocannon_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocannon',
            name='fecha',
            field=models.CharField(default='28/04/2025 10:01', help_text='Fecha y hora en que se registró el pago.', max_length=30, verbose_name='Fecha de pago'),
        ),
    ]
