# Generated by Django 4.2 on 2025-03-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_adelantos_usuario_descuentos_usuario_premios'),
        ('sales', '0004_metodopago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoexterno',
            name='agencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencia_movs', to='users.sucursal'),
        ),
        migrations.AlterField(
            model_name='movimientoexterno',
            name='ente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ente_movs', to='sales.cuentacobranza'),
        ),
        migrations.AlterField(
            model_name='movimientoexterno',
            name='metodoPago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metodo_movs', to='sales.metodopago'),
        ),
    ]
