# Generated by Django 4.2 on 2025-03-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_movimientoexterno_agencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoexterno',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones:'),
        ),
    ]
