# Generated by Django 4.2 on 2023-08-29 22:56

from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_ventas_nro_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='deBaja',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='nro_operacion',
            field=models.IntegerField(default=sales.models.Ventas.returnOperacion),
        ),
    ]
