# Generated by Django 4.2 on 2023-05-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_ventas_paquete_alter_ventas_tipo_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='importe',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='importe_x_cuota',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='intereses_generados',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='modalidad',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='nro_cuotas',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='nro_orden',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='nro_solicitud',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='paquete',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='tasa_interes',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='tipo_producto',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='total_a_pagar',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='vendedor',
        ),
    ]
