# Generated by Django 4.2 on 2025-04-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_rename_graded_auditoria_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='realizada',
        ),
    ]
