# Generated by Django 4.2 on 2023-05-07 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usuario_rango'),
        ('sales', '0006_remove_ventas_fecha_remove_ventas_importe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='nombre_completo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_nombre_cliente', to='users.cliente'),
            preserve_default=False,
        ),
    ]
