# Generated by Django 4.2 on 2025-05-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_auditoria_realizada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventas',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='ventas',
            name='is_commissionable',
            field=models.BooleanField(default=False, help_text='Indica si esta venta debe generar comisión para el vendedor a cargo', verbose_name='Venta apta para comisionar'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['agencia', 'campania'], name='sales_venta_agencia_65578c_idx'),
        ),
    ]
