# Generated by Django 4.2 on 2023-08-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_ventas_debaja_alter_ventas_nro_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='suspendida',
            field=models.BooleanField(default=False),
        ),
    ]
