# Generated by Django 4.2 on 2025-05-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_ventas_options_ventas_is_commissionable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='reintegro_dinero',
        ),
    ]
