# Generated by Django 4.2 on 2023-10-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_key_user_key_motivo'),
        ('sales', '0008_remove_ventas_tipo_adjudicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='clientes_anteriores',
            field=models.ManyToManyField(blank=True, related_name='ventas_anteriores', to='users.cliente'),
        ),
    ]
