# Generated by Django 4.2 on 2024-02-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_ventas_campania'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoexterno',
            name='adelanto',
            field=models.BooleanField(default=False, verbose_name='Adelanto:'),
        ),
        migrations.AddField(
            model_name='movimientoexterno',
            name='premio',
            field=models.BooleanField(default=False, verbose_name='Premio:'),
        ),
    ]
