# Generated by Django 4.2 on 2024-02-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_movimientoexterno_adelanto_movimientoexterno_premio'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoexterno',
            name='campania',
            field=models.IntegerField(default=0, verbose_name='Campaña:'),
        ),
    ]
