# Generated by Django 4.2 on 2023-10-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_ventas_cambiotitularidadfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='cambioTitularidadField',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
