# Generated by Django 4.2 on 2023-10-27 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_ventas_cambiotitularidadfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='clientes_anteriores',
        ),
    ]
