# Generated by Django 4.2 on 2024-05-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_ventas_adjudicado_alter_ventas_auditoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoexterno',
            name='hora',
        ),
    ]
