# Generated by Django 4.2 on 2024-05-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_remove_movimientoexterno_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoexterno',
            name='fecha',
            field=models.CharField(max_length=16, verbose_name='Fecha:'),
        ),
    ]
