# Generated by Django 4.2 on 2023-11-01 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0013_alter_ventas_agencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=30, verbose_name='Sucursal')),
                ('fecha', models.CharField(max_length=30, verbose_name='Fecha')),
                ('totalEfectivo', models.FloatField(default=0, verbose_name='Total efectivo')),
                ('totalPlanilla', models.FloatField(default=0, verbose_name='Total Planilla Efectivo')),
                ('totalSegunDiarioCaja', models.FloatField(default=0, verbose_name='Total segun diario de caja')),
                ('observaciones', models.TextField()),
                ('detalle', models.JSONField(default=list)),
                ('admin', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='arqueo_caja_admin', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='arqueo_caja_responsable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
