# Generated by Django 4.2 on 2023-11-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_arqueocaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocaja',
            name='diferencia',
            field=models.FloatField(default=0, verbose_name='Diferencia'),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='detalle',
            field=models.JSONField(default=dict),
        ),
    ]
