# Generated by Django 4.2 on 2024-07-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_movimientoexterno_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='nro_orden',
            field=models.CharField(default='', max_length=10, verbose_name='Nro de Orden:'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='nro_solicitud',
            field=models.CharField(default='', max_length=10, verbose_name='Nro solicitud:'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='tasa_interes',
            field=models.FloatField(default=0, verbose_name='Tasa de Interes:'),
        ),
    ]
