# Generated by Django 4.2 on 2023-11-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_arqueocaja_diferencia_alter_arqueocaja_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueocaja',
            name='admin',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='responsable',
            field=models.CharField(default='', max_length=70),
        ),
    ]
