# Generated by Django 4.2 on 2024-07-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_cuentacobranza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='adjudicado',
            field=models.JSONField(default={'autorizado_por': '', 'status': False, 'tipo': ''}),
        ),
    ]
