# Generated by Django 4.2 on 2023-11-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_arqueocaja_admin_alter_arqueocaja_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], default='', max_length=8, verbose_name='Movimiento:')),
                ('dinero', models.FloatField(default=0, verbose_name='Dinero:')),
                ('metodoPago', models.CharField(max_length=30, verbose_name='Metodo de pago:')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto:')),
                ('ente', models.CharField(max_length=40, verbose_name='Ente:')),
            ],
        ),
    ]
