# Generated by Django 4.2 on 2023-11-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_movimientoexterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoexterno',
            name='fecha',
            field=models.CharField(default='', max_length=10, verbose_name='Fecha:'),
        ),
    ]
