# Generated by Django 4.2 on 2024-07-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_ventas_adjudicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='cuotas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
