# Generated by Django 4.2 on 2023-11-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_movimientoexterno_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoexterno',
            name='movimiento',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=8, verbose_name='Movimiento:'),
        ),
    ]
