# Generated by Django 4.2 on 2023-11-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_movimientoexterno_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoexterno',
            name='dinero',
            field=models.FloatField(verbose_name='Dinero:'),
        ),
        migrations.AlterField(
            model_name='movimientoexterno',
            name='fecha',
            field=models.CharField(max_length=10, verbose_name='Fecha:'),
        ),
    ]
