# Generated by Django 4.2 on 2023-05-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_producto', models.CharField(choices=[('Prestamo', 'Prestamo'), ('Moto', 'Moto'), ('Electromestico', 'Electromestico')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('paquete', models.CharField(choices=[('Basico', 'Basico'), ('Estandar', 'Estandar'), ('Premium', 'Premium')], max_length=20)),
                ('importe', models.FloatField()),
            ],
        ),
    ]
