# Generated by Django 4.2 on 2024-11-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='valor_nominal',
        ),
        migrations.AddField(
            model_name='plan',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
