# Generated by Django 4.2 on 2024-11-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tipo_de_producto',
            field=models.CharField(choices=[('Solucion', 'Solucion'), ('Moto', 'Moto'), ('Combo', 'Combo')], max_length=20),
        ),
    ]
