# Generated by Django 4.2 on 2024-07-31 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='importe',
        ),
        migrations.AddField(
            model_name='products',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_producto', to='products.plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tipodePlan',
            field=models.CharField(choices=[('Basico', 'Basico'), ('Estandar', 'Estandar'), ('Premium', 'Premium')], max_length=8),
        ),
    ]
