# Generated by Django 4.2 on 2024-11-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_plan_valor_nominal_plan_id_products_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='precio',
        ),
        migrations.AddField(
            model_name='plan',
            name='valor_nominal',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
