# Generated by Django 4.2 on 2024-07-31 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_importe_products_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='paquete',
        ),
    ]
