# Generated by Django 4.2 on 2025-01-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_tipo_de_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tipo_de_producto',
            field=models.CharField(choices=[('Solucion', 'Solucion'), ('Moto', 'Moto'), ('Combo', 'Combo'), ('Default', 'Default')], max_length=20),
        ),
    ]
