# Generated by Django 4.2 on 2024-07-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_plan_cuota_1_remove_plan_suscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='c24_porcentage',
            field=models.FloatField(default=0, verbose_name='Porcentaje de 30 c'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='c30_porcentage',
            field=models.FloatField(default=0, verbose_name='Porcentaje de 24 c'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='c48_porcentage',
            field=models.FloatField(default=0, verbose_name='Porcentaje de 48 c'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='c60_porcentage',
            field=models.FloatField(default=0, verbose_name='Porcentaje de 60 c'),
        ),
    ]
