# Generated by Django 4.2 on 2024-08-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_plan_c24_porcentage_alter_plan_c30_porcentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='c24_porcentage',
            field=models.FloatField(default=0, verbose_name='Porcentaje de 24 c'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='c30_porcentage',
            field=models.FloatField(default=0, verbose_name='Porcentaje de 30 c'),
        ),
    ]
