# Generated by Django 4.2 on 2024-08-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_plan_c24_porcentage_alter_plan_c30_porcentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='primer_cuota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='suscripcion',
            field=models.IntegerField(default=0),
        ),
    ]
