# Generated by Django 4.2 on 2023-04-30 14:06

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('rango', models.CharField(choices=[('A', 'Admin'), ('G', 'Gerente'), ('S', 'Secretaria')], max_length=1, verbose_name='Rango')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('domic', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('prov', models.CharField(max_length=100, verbose_name='Provincia')),
                ('tel', models.IntegerField(verbose_name='Telefono')),
                ('fec_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('usuario_admin', models.BooleanField(default=False)),
                ('usuario_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_cliente', models.CharField(default=users.models.Cliente.returNro_Cliente, max_length=15)),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ ]+$', 'Ingrese solo letras')])),
                ('dni', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Ingrese un número válido')])),
                ('domic', models.CharField(max_length=100)),
                ('loc', models.CharField(max_length=40)),
                ('prov', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ ]+$', 'Ingrese solo letras')])),
                ('cod_postal', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Ingrese un número válido')])),
                ('tel', models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Ingrese un número válido')])),
                ('fec_nacimiento', models.DateField()),
                ('estado_civil', models.CharField(max_length=20)),
                ('ocupacion', models.CharField(max_length=50)),
            ],
        ),
    ]
