# Generated by Django 4.2 on 2023-12-28 20:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_cliente', models.CharField(default=users.models.Cliente.returNro_Cliente, max_length=15)),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ ]+$', 'Ingrese solo letras')])),
                ('dni', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Ingrese un número válido')])),
                ('agencia_registrada', models.CharField(default='', max_length=30)),
                ('domic', models.CharField(max_length=100)),
                ('loc', models.CharField(max_length=40)),
                ('prov', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ ]+$', 'Ingrese solo letras')])),
                ('cod_postal', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Ingrese un número válido')])),
                ('tel', models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Ingrese un número válido')])),
                ('fec_nacimiento', models.CharField(default='', max_length=30)),
                ('estado_civil', models.CharField(max_length=20)),
                ('ocupacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(default='', max_length=20)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('hora_apertura', models.CharField(max_length=5, verbose_name='Hora de apertura')),
                ('provincia', models.CharField(max_length=80, verbose_name='Provincia')),
                ('localidad', models.CharField(max_length=80, verbose_name='Localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('rango', models.CharField(max_length=40, verbose_name='Rango:')),
                ('dni', models.CharField(blank=True, max_length=8, null=True, verbose_name='DNI')),
                ('tel', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefono')),
                ('c', models.CharField(max_length=250, verbose_name='Contraseña_depuracion:')),
                ('domic', models.CharField(default='', max_length=200, verbose_name='Domicilio')),
                ('prov', models.CharField(default='', max_length=40, verbose_name='Provincia')),
                ('cp', models.CharField(default='', max_length=5, verbose_name='Codigo postal')),
                ('loc', models.CharField(default='', max_length=100, verbose_name='Localidad')),
                ('lugar_nacimiento', models.CharField(default='', max_length=100, verbose_name='Lugar de nacimiento')),
                ('fec_nacimiento', models.CharField(default='', max_length=10, verbose_name='Fecha de nacimiento')),
                ('estado_civil', models.CharField(default='', max_length=30, verbose_name='Estado civil')),
                ('xp_laboral', models.TextField(default='', verbose_name='Experiencia laboral')),
                ('datos_familiares', models.JSONField(blank=True, default=list, null=True, verbose_name='Datos familiares')),
                ('vendedores_a_cargo', models.JSONField(blank=True, default=list, null=True, verbose_name='Vendedores a cargo')),
                ('faltas_tardanzas', models.JSONField(blank=True, default=list, null=True, verbose_name='Faltas o tardanzas')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.sucursal')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
