# Generated by Django 4.2 on 2025-04-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='email_ref',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Email de referencia'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='tel_ref',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono de referencia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fec_egreso',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Fecha de egreso'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='generico_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='premios',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Premios'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='suspendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fec_nacimiento',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
