# Generated by Django 4.2 on 2025-04-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fec_egreso',
            field=models.CharField(blank='', default='', max_length=10, verbose_name='Fecha de egreso'),
        ),
    ]
