# Generated by Django 4.2 on 2024-11-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='descuentos',
            new_name='adelantos',
        ),
    ]
