# Generated by Django 4.2 on 2023-04-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='domic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fec_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='prov',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
    ]
