# Generated by Django 4.2 on 2023-04-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_dni_alter_usuario_domic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rango',
            field=models.CharField(choices=[('A', 'Admin'), ('G', 'Gerente'), ('S', 'Secretaria')], max_length=1, verbose_name='Rango: A/G/S'),
        ),
    ]
