# Generated by Django 4.2 on 2024-10-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_sucursales'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descuentos',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Descuentos'),
        ),
    ]
