# Generated by Django 4.2 on 2024-02-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fec_ingreso',
            field=models.CharField(default='', max_length=10, verbose_name='Fecha de ingreso'),
        ),
    ]
