# Generated by Django 4.2 on 2024-11-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_descuentos_usuario_adelantos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='adelantos',
            new_name='descuentos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='premios',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Premios'),
        ),
    ]
