# Generated by Django 4.2 on 2025-04-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sucursal_email_ref_sucursal_tel_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
