# Generated by Django 4.2 on 2024-02-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_fec_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='sucursal_central',
            field=models.BooleanField(default=False),
        ),
    ]
