# Generated by Django 4.2 on 2024-10-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_descuentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='agencia_registrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente_sucursal', to='users.sucursal'),
        ),
    ]
