# Generated by Django 4.2 on 2025-03-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_adelantos_usuario_descuentos_usuario_premios'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='email_ref',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Email de referencia'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='tel_ref',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono de referencia'),
        ),
    ]
