# Generated by Django 4.2 on 2023-05-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usuario_rango'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rango',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Gerenete', 'Gerente'), ('Secreteria', 'Secretaria')], max_length=15, verbose_name='Rango: A/G/S'),
        ),
    ]
