# Generated by Django 4.2 on 2025-04-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_suspendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fec_egreso',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Fecha de egreso'),
        ),
    ]
