# Generated by Django 4.2 on 2023-10-24 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_key_user_key_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tel',
            field=models.IntegerField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Ingrese un número válido')]),
        ),
    ]
