# Generated by Django 4.2 on 2025-04-29 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_cliente_estado_civil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='descuentos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='faltas_tardanzas',
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de aplicación del descuento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(help_text='¿Por qué se aplica?', max_length=100)),
                ('usuario', models.ForeignKey(help_text='Usuario al que corresponde este descuento', on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Día de la falta/tardanza')),
                ('tipo', models.CharField(choices=[('Falta', 'Falta'), ('Tardanza', 'Tardanza')], max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(help_text='Usuario al que corresponde esta falta o tardanza', on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ausencia/Tardanza',
                'verbose_name_plural': 'Ausencias/Tardanzas',
                'ordering': ['-fecha'],
            },
        ),
    ]
