# Generated by Django 4.2 on 2025-04-29 21:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_usuario_descuentos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausencia',
            options={'ordering': ['-fecha_de_carga'], 'verbose_name': 'Ausencia/Tardanza', 'verbose_name_plural': 'Ausencias/Tardanzas'},
        ),
        migrations.RemoveField(
            model_name='ausencia',
            name='fecha',
        ),
        migrations.AddField(
            model_name='ausencia',
            name='dia',
            field=models.CharField(default='', help_text='Día de falta/tardanza', max_length=10),
        ),
        migrations.AddField(
            model_name='ausencia',
            name='fecha_de_carga',
            field=models.CharField(default=users.models.Ausencia.now_formatted, help_text='Día de carga de falta/tardanza', max_length=20),
        ),
        migrations.AddField(
            model_name='ausencia',
            name='hora',
            field=models.CharField(default='', help_text='Hora de falta/tardanza', max_length=5),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='fecha',
            field=models.CharField(default=users.models.Descuento.now_formatted, help_text='Fecha de aplicación del descuento', max_length=20),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='monto',
            field=models.IntegerField(default=0, help_text='Monto del descuento'),
        ),
    ]
