# Generated by Django 4.2 on 2023-10-24 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_cliente_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tel',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Ingrese un número válido')]),
        ),
    ]
