# Generated by Django 4.2 on 2024-10-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_cliente_agencia_registrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cod_postal',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='domic',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='loc',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='prov',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel',
            field=models.CharField(default='', max_length=11),
        ),
    ]
