# Generated by Django 4.2 on 2025-04-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usuario_fec_egreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fec_nacimiento',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
