# Generated by Django 4.2 on 2025-04-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_sucursal_email_ref_sucursal_tel_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='generico_user',
            field=models.BooleanField(default=False),
        ),
    ]
