# Generated by Django 4.2 on 2025-05-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_ausencia_options_remove_ausencia_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausencia',
            name='campania',
            field=models.CharField(blank=True, max_length=30, verbose_name='Campaña'),
        ),
    ]
