# Generated by Django 4.2 on 2024-05-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_sucursal_pseudonimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='accesosTodasSucursales',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='xp_laboral',
            field=models.TextField(default='Vacio', verbose_name='Experiencia laboral'),
        ),
    ]
