# Generated by Django 4.2 on 2023-05-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usuario_usuario_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rango',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Gerenete', 'Gerente'), ('Secreteria', 'Secretaria')], max_length=15, verbose_name='Rango:'),
        ),
    ]
