# Generated by Django 4.2 on 2023-10-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_cliente_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sucursal',
            field=models.CharField(choices=[('resistencia_chaco', 'Resistencia, Chaco '), ('saenzPenia_chaco', 'Saenz Peña, Chaco '), ('corrientes_corrientes', 'Corrientes, Corrientes '), ('misiones_misiones', 'Misiones, Misiones')], default='', max_length=30, verbose_name='Agencia'),
        ),
    ]
