# Generated by Django 4.2 on 2023-10-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usuario_sucursal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rango',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Gerente', 'Gerente'), ('Secreteria', 'Secretaria'), ('Vendedor', 'Vendedor'), ('Supervisor', 'Supervisor')], max_length=15, verbose_name='Rango:'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sucursal',
            field=models.CharField(choices=[('Resistencia, Chaco', 'Resistencia, Chaco'), ('Saenz Peña, Chaco', 'Saenz Peña, Chaco'), ('Corrientes, Corrientes', 'Corrientes, Corrientes'), ('Misiones, Misiones', 'Misiones, Misiones')], default='', max_length=30, verbose_name='Agencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tel',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_admin',
            field=models.BooleanField(default=False),
        ),
    ]
