# Generated by Django 4.2 on 2024-05-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usuario_accesostodassucursales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='descripcion',
            field=models.CharField(default='', max_length=255),
        ),
    ]
