# Generated by Django 4.2 on 2023-05-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usuario_rango'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('puede_ver_algo', 'Puede ver algo'), ('puede_cambiar_algo', 'Puede cambiar algo'), ('puede_borrar_algo', 'Puede eliminar algo')]},
        ),
    ]
