# Generated by Django 4.2 on 2025-05-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_ausencia_campania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tel',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono'),
        ),
    ]
