# Generated by Django 4.2 on 2023-10-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usuario_options_alter_usuario_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sucursal',
            field=models.CharField(choices=[('Resistencia, Chaco', 'Resistencia, Chaco'), ('Saenz Peña, Chaco', 'Saenz Peña, Chaco'), ('Corrientes, Corrientes', 'Corrientes, Corrientes'), ('Misiones, Misiones', 'Misiones, Misiones')], default='', max_length=30, verbose_name='Sucursal'),
        ),
    ]
