# Generated by Django 4.2 on 2025-05-22 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_cliente_dni_alter_usuario_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUsuario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Correo Electrónico')),
                ('rango', models.CharField(max_length=40, verbose_name='Rango:')),
                ('dni', models.CharField(blank=True, max_length=12, null=True, verbose_name='DNI')),
                ('tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono')),
                ('c', models.CharField(max_length=250, verbose_name='Contraseña_depuracion:')),
                ('fec_ingreso', models.CharField(default='', max_length=10, verbose_name='Fecha de ingreso')),
                ('fec_egreso', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Fecha de egreso')),
                ('domic', models.CharField(default='', max_length=200, verbose_name='Domicilio')),
                ('prov', models.CharField(default='', max_length=40, verbose_name='Provincia')),
                ('cp', models.CharField(default='', max_length=5, verbose_name='Codigo postal')),
                ('loc', models.CharField(default='', max_length=100, verbose_name='Localidad')),
                ('lugar_nacimiento', models.CharField(default='', max_length=100, verbose_name='Lugar de nacimiento')),
                ('fec_nacimiento', models.CharField(default='', max_length=10, verbose_name='Fecha de nacimiento')),
                ('estado_civil', models.CharField(default='', max_length=30, verbose_name='Estado civil')),
                ('xp_laboral', models.TextField(blank=True, default='', null=True, verbose_name='Experiencia laboral')),
                ('premios', models.JSONField(blank=True, default=list, null=True, verbose_name='Premios')),
                ('datos_familiares', models.JSONField(blank=True, default=list, null=True, verbose_name='Datos familiares')),
                ('vendedores_a_cargo', models.JSONField(blank=True, default=list, null=True, verbose_name='Vendedores a cargo')),
                ('additional_passwords', models.JSONField(blank=True, default=dict, null=True, verbose_name='Contraseñas adicionales')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('accesosTodasSucursales', models.BooleanField(default=False)),
                ('generico_user', models.BooleanField(default=False)),
                ('suspendido', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical usuario',
                'verbose_name_plural': 'historical usuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
