# Generated by Django 4.2 on 2023-05-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usuario_rango'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fec_nacimiento',
            field=models.CharField(default='', max_length=30),
        ),
    ]
