# Generated by Django 4.2 on 2023-10-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usuario_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='agencia_registrada',
            field=models.CharField(default='', max_length=30),
        ),
    ]
