# Generated by Django 4.2 on 2024-07-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_cliente_cod_postal_alter_cliente_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='xp_laboral',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Experiencia laboral'),
        ),
    ]
