# Generated by Django 4.2 on 2024-07-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usuario_dni_alter_usuario_xp_laboral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cod_postal',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='prov',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel',
            field=models.CharField(max_length=11),
        ),
    ]
