# Generated by Django 4.2 on 2025-06-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_historicalusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuario',
            name='cp',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Codigo postal'),
        ),
        migrations.AlterField(
            model_name='historicalusuario',
            name='domic',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='historicalusuario',
            name='estado_civil',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='historicalusuario',
            name='fec_nacimiento',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='historicalusuario',
            name='loc',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='historicalusuario',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AlterField(
            model_name='historicalusuario',
            name='prov',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cp',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Codigo postal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='domic',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_civil',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fec_nacimiento',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='loc',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='prov',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Provincia'),
        ),
    ]
