# Generated by Django 4.2 on 2024-07-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_cliente_cod_postal_alter_cliente_dni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='gerente',
            field=models.CharField(default='', max_length=100, verbose_name='Gerente'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sucursales',
            field=models.ManyToManyField(related_name='sucursales_usuarios', to='users.sucursal'),
        ),
    ]
