# Generated by Django 4.2 on 2025-06-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_historicalusuario_email_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuario',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, unique=True, verbose_name='Correo Electrónico'),
        ),
    ]
