# Generated by Django 4.2 on 2024-07-15 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_usuario_sucursal_sucursal_gerente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='gerente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gerente', to=settings.AUTH_USER_MODEL),
        ),
    ]
