# Generated by Django 4.2 on 2025-06-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_historicalusuario_email_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cod_postal',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='domic',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='loc',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='prov',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
