# Generated by Django 4.2 on 2024-07-16 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_sucursal_gerente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='gerente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gerente', to=settings.AUTH_USER_MODEL),
        ),
    ]
