# Generated by Django 4.2 on 2025-11-05 13:05

from django.db import migrations, models, transaction
from django.db.models import IntegerField, Max
from django.db.models.functions import Cast, Substr


PAD = 3  # cli_001, cli_002, ...


def dedupe_clientes(apps, schema_editor):
    """Renumera duplicados (agencia_registrada, nro_cliente) antes de agregar el UniqueConstraint."""
    Cliente = apps.get_model('users', 'Cliente')
    db = schema_editor.connection.alias

    with transaction.atomic(using=db):
        # Buscar pares duplicados
        dups = (
            Cliente.objects.using(db)
            .values('agencia_registrada_id', 'nro_cliente')
            .annotate(c=models.Count('id'))
            .filter(c__gt=1)
        )

        for d in dups:
            aid = d['agencia_registrada_id']
            nro = d['nro_cliente']

            # Mantener la 1ª fila y renumerar el resto
            ids = list(
                Cliente.objects.using(db)
                .filter(agencia_registrada_id=aid, nro_cliente=nro)
                .order_by('id')
                .values_list('id', flat=True)
            )

            # Máximo número actual en esa agencia (parte numérica de cli_###)
            max_n = (
                Cliente.objects.using(db)
                .filter(agencia_registrada_id=aid)
                .annotate(n=Cast(Substr('nro_cliente', 5), IntegerField()))
                .aggregate(m=Max('n'))['m']
            ) or 0

            next_n = max_n + 1
            for cid in ids[1:]:
                new_code = f"cli_{next_n:0{PAD}d}"
                # Evitar colisiones por si ya existe ese código
                while Cliente.objects.using(db).filter(agencia_registrada_id=aid, nro_cliente=new_code).exists():
                    next_n += 1
                    new_code = f"cli_{next_n:0{PAD}d}"
                Cliente.objects.using(db).filter(pk=cid).update(nro_cliente=new_code)
                next_n += 1


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_cliente_cod_postal_alter_cliente_domic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombre']},
        ),
        # 1) Saneamos duplicados antes de imponer la unicidad
        migrations.RunPython(dedupe_clientes, migrations.RunPython.noop),
        # 2) Ahora sí, agregamos el constraint único
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(
                fields=('agencia_registrada', 'nro_cliente'),
                name='uniq_nro_cliente_por_agencia',
            ),
        ),
    ]
