# Generated by Django 4.2 on 2025-11-05 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusuario',
            name='supervisores_a_cargo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='supervisores_a_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_a_cargo', to=settings.AUTH_USER_MODEL),
        ),
    ]
