# Generated by Django 4.2 on 2024-07-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_usuario_sucursales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sucursales',
            field=models.ManyToManyField(blank=True, null=True, related_name='sucursales_usuarios', to='users.sucursal'),
        ),
    ]
