# Generated by Django 4.2 on 2026-03-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_historicalusuario_supervisores_a_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='uniq_nro_cliente_por_agencia',
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('agencia_registrada', 'nro_cliente', 'dni'), name='uniq_nro_cliente_dni_por_agencia'),
        ),
    ]
