# Generated by Django 4.2 on 2024-07-28 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_usuario_sucursales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='gerente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gerente', to=settings.AUTH_USER_MODEL),
        ),
    ]
