# Generated by Django 4.2 on 2026-03-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_cliente_uniq_nro_cliente_por_agencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusuario',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Alias bancario'),
        ),
        migrations.AddField(
            model_name='historicalusuario',
            name='cbu',
            field=models.CharField(blank=True, default='', max_length=22, null=True, verbose_name='CBU'),
        ),
        migrations.AddField(
            model_name='historicalusuario',
            name='entidad_bancaria',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Entidad Bancaria'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Alias bancario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cbu',
            field=models.CharField(blank=True, default='', max_length=22, null=True, verbose_name='CBU'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='entidad_bancaria',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Entidad Bancaria'),
        ),
    ]
