# Generated by Django 4.2 on 2024-07-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_sucursal_gerente'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='camapania',
            field=models.IntegerField(default=0, verbose_name='Campaña'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='fecha_innaguracion',
            field=models.CharField(default='', max_length=10, verbose_name='Fecha de innaguración'),
        ),
    ]
