# Generated by Django 4.2 on 2024-07-30 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_sucursal_camapania_sucursal_fecha_innaguracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursal',
            old_name='camapania',
            new_name='campania',
        ),
    ]
