# Generated by Django 4.2 on 2024-08-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_camapania_sucursal_campania'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='campania',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='fecha_innaguracion',
        ),
    ]
