<<<<<<< HEAD
# Generated by Django 4.2 on 2024-08-04 20:31
=======
# Generated by Django 4.2 on 2024-08-03 13:05
>>>>>>> 4368eaa8a750f3a82cf0032a3d7b390ab7cab2eb

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_camapania_sucursal_campania'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='campania',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='fecha_innaguracion',
        ),
    ]
