# Generated by Django 4.2 on 2024-02-14 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_usuario_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoeficientePorCantidadSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('coeficiente', models.FloatField(verbose_name='Coeficiente')),
            ],
        ),
        migrations.CreateModel(
            name='CoeficientePorCantidadVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('com_48_60', models.IntegerField(verbose_name='48/60 Cuotas')),
                ('com_24_30_motos', models.IntegerField(verbose_name='24/30 Cuotas Motos')),
                ('com_24_30_elec_soluc', models.IntegerField(verbose_name='24/30 Cuotas Elec/Soluc')),
            ],
        ),
        migrations.CreateModel(
            name='CoeficientePorProductividadSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinero', models.IntegerField(verbose_name='Dinero')),
                ('coeficiente', models.FloatField(verbose_name='Coeficiente')),
            ],
        ),
        migrations.CreateModel(
            name='CoeficientePorProductividadVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinero', models.IntegerField(verbose_name='Dinero')),
                ('premio', models.FloatField(verbose_name='Premio')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionCompleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=8, verbose_name='Fecha')),
                ('camapania', models.IntegerField(verbose_name='Camapaña')),
                ('total_liquidado', models.FloatField(verbose_name='Total liquidado')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campania', models.IntegerField(verbose_name='Campaña')),
                ('cant_ventas', models.IntegerField(verbose_name='Cantidad de ventas')),
                ('productividad', models.FloatField(verbose_name='Productividad')),
                ('total_comisionado', models.FloatField(verbose_name='Total comisionado')),
                ('detalle', models.JSONField(default=dict)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campania', models.IntegerField(verbose_name='Campaña')),
                ('cant_ventas', models.IntegerField(verbose_name='Cantidad de ventas')),
                ('total_comisionado', models.FloatField(verbose_name='Total comisionado')),
                ('detalle', models.JSONField(default=dict)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionGerenteSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campania', models.IntegerField(verbose_name='Campaña')),
                ('total_comisionado', models.FloatField(verbose_name='Total comisionado')),
                ('detalle', models.JSONField(default=dict)),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.sucursal')),
            ],
        ),
    ]
