# Generated by Django 4.2 on 2024-02-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asegurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinero', models.IntegerField(verbose_name='Dinero')),
                ('dirigido', models.CharField(max_length=80, verbose_name='Dirigido')),
            ],
        ),
    ]
