# Generated by Django 4.2 on 2024-08-09 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('liquidacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionvendedor',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidacionsupervisor',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidaciongerentesucursal',
            name='gerente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidaciongerentesucursal',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.sucursal'),
        ),
        migrations.AddField(
            model_name='liquidacioncompleta',
            name='detalle_admins',
            field=models.ManyToManyField(blank=True, to='liquidacion.liquidacionadmin'),
        ),
        migrations.AddField(
            model_name='liquidacioncompleta',
            name='detalle_gerentes',
            field=models.ManyToManyField(blank=True, to='liquidacion.liquidaciongerentesucursal'),
        ),
        migrations.AddField(
            model_name='liquidacioncompleta',
            name='detalle_supervisores',
            field=models.ManyToManyField(blank=True, to='liquidacion.liquidacionsupervisor'),
        ),
        migrations.AddField(
            model_name='liquidacioncompleta',
            name='detalle_vendedores',
            field=models.ManyToManyField(blank=True, to='liquidacion.liquidacionvendedor'),
        ),
        migrations.AddField(
            model_name='liquidacionadmin',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidacionadmin',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.sucursal'),
        ),
    ]
