# Generated by Django 4.2 on 2025-06-27 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_cliente_cod_postal_alter_cliente_domic_and_more'),
        ('liquidacion', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campania', models.CharField(max_length=50, verbose_name='Campaña')),
                ('fecha', models.CharField(max_length=15, verbose_name='Fecha')),
                ('json_data_liquidacion', models.JSONField(default=list)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='liquidacion_agencia', to='users.sucursal')),
            ],
        ),
    ]
