# Generated by Django 4.2 on 2024-09-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontoTardanzaAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_tardanza', models.DecimalField(decimal_places=2, default=350.0, max_digits=6)),
                ('monto_ausencia', models.DecimalField(decimal_places=2, default=2000.0, max_digits=6)),
                ('margen_tiempo', models.IntegerField(default=15)),
            ],
        ),
    ]
