# Generated by Django 4.2 on 2025-01-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0003_rename_camapania_liquidacioncompleta_campania_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacioncompleta',
            name='total_proyectado',
            field=models.FloatField(default=0, verbose_name='Total proyectado'),
        ),
    ]
