# Generated by Django 4.2 on 2025-07-11 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0003_liquidacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacioncompleta',
            name='detalle_admins',
        ),
        migrations.RemoveField(
            model_name='liquidacioncompleta',
            name='detalle_gerentes',
        ),
        migrations.RemoveField(
            model_name='liquidacioncompleta',
            name='detalle_supervisores',
        ),
        migrations.RemoveField(
            model_name='liquidacioncompleta',
            name='detalle_vendedores',
        ),
        migrations.RemoveField(
            model_name='liquidacioncompleta',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='liquidaciongerentesucursal',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='liquidaciongerentesucursal',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='liquidacionsupervisor',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='liquidacionsupervisor',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='liquidacionvendedor',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='liquidacionvendedor',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='LiquidacionAdmin',
        ),
        migrations.DeleteModel(
            name='LiquidacionCompleta',
        ),
        migrations.DeleteModel(
            name='LiquidacionGerenteSucursal',
        ),
        migrations.DeleteModel(
            name='LiquidacionSupervisor',
        ),
        migrations.DeleteModel(
            name='LiquidacionVendedor',
        ),
    ]
