# Generated by Django 4.2 on 2025-01-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0004_liquidacioncompleta_total_proyectado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacionadmin',
            name='campania',
            field=models.CharField(max_length=50, verbose_name='Campaña'),
        ),
        migrations.AlterField(
            model_name='liquidacioncompleta',
            name='campania',
            field=models.CharField(max_length=50, verbose_name='Campaña'),
        ),
        migrations.AlterField(
            model_name='liquidaciongerentesucursal',
            name='campania',
            field=models.CharField(max_length=50, verbose_name='Campaña'),
        ),
        migrations.AlterField(
            model_name='liquidacionsupervisor',
            name='campania',
            field=models.CharField(max_length=50, verbose_name='Campaña'),
        ),
        migrations.AlterField(
            model_name='liquidacionvendedor',
            name='campania',
            field=models.CharField(max_length=50, verbose_name='Campaña'),
        ),
    ]
