# Generated by Django 4.2 on 2026-03-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0004_remove_liquidacioncompleta_detalle_admins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='cant_ventas',
            field=models.IntegerField(default=0, verbose_name='Cantidad de ventas'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='cerrada',
            field=models.BooleanField(default=False, verbose_name='Cerrada'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='config_snapshot',
            field=models.JSONField(default=dict, verbose_name='Snapshot de configuración'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='total_liquidado',
            field=models.FloatField(default=0, verbose_name='Total liquidado'),
        ),
    ]
