# Generated by Django 4.2 on 2024-02-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0004_asegurado_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionsupervisor',
            name='productividad',
            field=models.FloatField(default=0, verbose_name='Productividad'),
        ),
    ]
