# Generated by Django 4.2 on 2024-02-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0005_liquidacionsupervisor_productividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coeficienteporcantidadsupervisor',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='coeficienteporcantidadvendedor',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='coeficienteporcantidadsupervisor',
            name='cantidad_maxima',
            field=models.IntegerField(default=0, verbose_name='Cantidad maxima'),
        ),
        migrations.AddField(
            model_name='coeficienteporcantidadsupervisor',
            name='cantidad_minima',
            field=models.IntegerField(default=0, verbose_name='Cantidad minima'),
        ),
        migrations.AddField(
            model_name='coeficienteporcantidadvendedor',
            name='cantidad_maxima',
            field=models.IntegerField(default=0, verbose_name='Cantidad maxima'),
        ),
        migrations.AddField(
            model_name='coeficienteporcantidadvendedor',
            name='cantidad_minima',
            field=models.IntegerField(default=0, verbose_name='Cantidad minima'),
        ),
    ]
