# Generated by Django 4.2 on 2026-03-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0005_liquidacion_cant_ventas_liquidacion_cerrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia_desde', models.DateField(verbose_name='Vigente desde')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('parametros', models.JSONField(verbose_name='Parámetros')),
            ],
            options={
                'verbose_name': 'Configuración de liquidación',
                'verbose_name_plural': 'Configuraciones de liquidación',
                'ordering': ['-vigencia_desde'],
            },
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='es_vigente',
            field=models.BooleanField(default=True, verbose_name='Es vigente'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='motivo_reliquidacion',
            field=models.TextField(blank=True, default='', verbose_name='Motivo de reliquidación'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Versión'),
        ),
    ]
