# Generated by Django 4.2 on 2025-03-25 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_sucursal_email_ref_sucursal_tel_ref'),
        ('liquidacion', '0007_remove_asegurado_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionsupervisor',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.sucursal'),
        ),
        migrations.AddField(
            model_name='liquidacionvendedor',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.sucursal'),
        ),
    ]
