# Generated by Django 4.2 on 2026-03-04 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_historicalusuario_supervisores_a_cargo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liquidacion', '0008_add_asegurado_a_config_y_drop_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campania', models.CharField(max_length=50, verbose_name='Campaña')),
                ('ajuste_tipo', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo')], max_length=10, verbose_name='Tipo')),
                ('dinero', models.PositiveIntegerField(verbose_name='Monto')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_comision', to='users.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_comision', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste de comisión',
                'verbose_name_plural': 'Ajustes de comisión',
                'ordering': ['creado_en'],
            },
        ),
    ]
