# Generated by Django 4.2 on 2026-05-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0009_ajustecomision'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustecomision',
            name='fecha_ajuste',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha ajuste'),
        ),
    ]
